baseURL = "http://giuliobosco.github.io/"
languageCode = "en-us"
title = "giuliobosco.ch"
theme = "smol"
github = "https://github.com/giuliobosco/"

# Parameters
[params]
    subtitle = ""
    dateFmt = "2006.01.02 15:04"
    description = "I'm Giulio Bosco based in Lugano, Switzerland. Work: SAP B1 Users Operations Support at Drytech International SA. Skills: Team work, Coding, Systems"

# Header
[menu]
  [[menu.main]]
        identifier = "home"
        name = "start"
        title = "start"
        url = "/"
        weight = 1
  [[menu.main]]
        identifier = "projects"
        name = "projects"
        title = "start"
        url = "/projects/"
        weight = 2

  [[menu.main]]
        identifier = "experiences"
        name = "experiences"
        title = "start"
        url = "/experiences/"
        weight = 3

  [[menu.main]]
        identifier = "education"
        name = "education"
        title = "start"
        url = "/education/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/giuliobosco"
        weight = 1 

    [[menu.footer]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/giulio-bosco-91a728127/"
        weight = 2 

    [[menu.footer]]
        name = "Instagram"
        url = "https://www.instagram.com/giulio___01/"
        weight = 3 

#    [[menu.footer]]
#        name = "About"
#        url = "/about/"
#        weight = 4
