name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Deploy branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup identity
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

    - name: Install Hugo
      run: |
        cd ..
        git clone https://github.com/gohugoio/hugo.git
        cd hugo
        go install
        ls ~/go/bin

    - name: Build Hugo
      run: ~/go/bin/hugo

    - name: Run deploy script
      run: ./deploy.sh
